# rag/rag_chain.py

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.chat_history import BaseChatMessageHistory, InMemoryChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.runnables import RunnableLambda, RunnablePassthrough, RunnableBranch
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document
from langchain_core.globals import set_llm_cache
from langchain_community.cache import SQLiteCache
from config import GROQ_API_KEY, LLM_MODEL, LLM_CACHE_FILE, CACHE_DIR, CHAT_HISTORY_WINDOW

os.makedirs(CACHE_DIR, exist_ok=True)
set_llm_cache(SQLiteCache(database_path=LLM_CACHE_FILE))

_session_histories: dict[str, InMemoryChatMessageHistory] = {}


def get_session_history(session_id: str) -> BaseChatMessageHistory:
    """Return (and lazily create) the chat history for a session.

    Trims to the last CHAT_HISTORY_WINDOW * 2 messages (one human + one AI per turn).
    """
    history = _session_histories.get(session_id)
    if history is None:
        history = InMemoryChatMessageHistory()
        _session_histories[session_id] = history
    max_msgs = CHAT_HISTORY_WINDOW * 2
    if len(history.messages) > max_msgs:
        history.messages = history.messages[-max_msgs:]
    return history


def get_llm() -> ChatGroq:
    llm = ChatGroq(
        api_key=GROQ_API_KEY,
        model_name=LLM_MODEL,
        temperature=0.2,
    )
    print(f"✅ LLM loaded: {LLM_MODEL} via ChatGroq (SQLite response cache active)")
    return llm


def _format_tagged_context(docs: list[Document]) -> str:
    lines = []
    for d in docs:
        tag = "TEXT" if d.metadata.get("source_type") == "text" else "IMAGE"
        lines.append(f"[{tag}] {d.page_content}")
    return "\n\n".join(lines)


def build_rag_chain(retriever, llm: ChatGroq):
    """
    History-aware conversational RAG chain built with pure LCEL.

    Flow:
      1. If chat_history is non-empty, rewrite the question into a standalone
         one using the history (so retrieval understands follow-ups).
      2. Retrieve top-K chunks for that standalone question.
      3. Format chunks with [TEXT]/[IMAGE] source tags.
      4. Answer with the LLM, given context + chat_history + original input.
      5. Wrap everything with RunnableWithMessageHistory so per-session
         history is loaded/saved automatically.
    """
    contextualize_prompt = ChatPromptTemplate.from_messages([
        ("system",
         "Given the chat history and the latest user question, rewrite the "
         "question as a standalone question that can be understood without "
         "the chat history. Do NOT answer it; only reformulate it. If the "
         "question is already standalone, return it unchanged."),
        MessagesPlaceholder("chat_history"),
        ("human", "{input}"),
    ])

    contextualize_question = contextualize_prompt | llm | StrOutputParser()

    # Only rewrite when there is history; otherwise use the raw input.
    question_for_retrieval = RunnableBranch(
        (
            lambda x: bool(x.get("chat_history")),
            contextualize_question,
        ),
        (lambda x: x["input"]),
    )

    qa_system_prompt = (
        "You are a helpful and knowledgeable assistant.\n"
        "Use the retrieved context below to answer the user's question.\n\n"
        "The context contains snippets from two source types:\n"
        "- [TEXT]  — extracted directly from the document text. Treat as authoritative.\n"
        "- [IMAGE] — generated by a vision model describing embedded images. Use only "
        "as supporting detail; prefer [TEXT] when the two disagree, and never treat "
        "[IMAGE] descriptions as exact quotes from the document.\n\n"
        "If the answer is not in the context, say "
        "\"I don't have enough information to answer that.\"\n\n"
        "Context:\n{context}"
    )

    qa_prompt = ChatPromptTemplate.from_messages([
        ("system", qa_system_prompt),
        MessagesPlaceholder("chat_history"),
        ("human", "{input}"),
    ])

    # Compose: retrieve → format → answer.
    rag_chain = (
        RunnablePassthrough.assign(
            context=question_for_retrieval | retriever | RunnableLambda(_format_tagged_context),
        )
        | RunnablePassthrough.assign(
            answer=qa_prompt | llm | StrOutputParser(),
        )
    )

    conversational_rag_chain = RunnableWithMessageHistory(
        rag_chain,
        get_session_history,
        input_messages_key="input",
        history_messages_key="chat_history",
        output_messages_key="answer",
    )

    return conversational_rag_chain
